apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  labels:
    app: react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - image: vikiardian/react-app:5
        name: react-app
        args:
        - liveness
        livenessProbe:
          httpGet:
            path: /
            port: 3000
        initialDelaySeconds: 3
        periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: react-service
  labels:
    app: react-service
spec:
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 31234
  type: NodePort
