apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  labels:
    app: react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - image: vikiardian/react-app:3
        name: react-app
        resources: {}
status: {}
---

apiVersion: v1
kind: Service
metadata:
  name: ract-service
  labels:
    app: react-service
spec:
  type: NodePort
  ports:
  - port: 443
    targetPort: 3000
    nodePort: 30123
  selector:
    app: react
